---
apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: my-deployment
  labels:
    env: dev

spec:
  replicas: 3
  selector: 
    matchLabels:
      env: dev

  template: 
    metadata:
      labels: 
        env: dev
    spec: 
      containers:
        - name: cbdc-pod
          image: httpd
          ports:  
            - containerPort: 80
...
---
apiVersion: v1 

