apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: three-tier-app-dep-mysql
  labels: 
    app: three-tier-app-mysql
spec:
  replicas: 1 
  selector: 
    matchLabels: 
      app: three-tier-app-mysql
  template:
    metadata:
      labels: 
        app: three-tier-app-mysql
    spec: 
      containers:
        - name: mysql-app
          image: mysql:8
          
          ports:
            - containerPort: 3306

          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootpassword
            - name: MYSQL_DATABASE
              value: appdb
            - name: MYSQL_USER
              value: appuser
            - name: MYSQL_PASSWORD
              value: appuserpass

          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql

