apiVersion: v1
kind: PersistentVolumeClaim 
metadata: 
  name: three-tier-app-pvc
  labels:
    app: three-tier-app-mysql
spec: 
  accessModes: 
    - ReadWriteOnce
  resources:
    requests: 
      storage: 1Gi
  storageClassName: gp2
