apiVersion: v1 
kind: Service 
metadata: 
  name: three-tier-app-svc
  labels: 
    app: three-tier-app-mysql
spec: 
  selector: 
    app: three-tier-app-mysql
  ports:
    - port: 3306
  clusterIP: None