AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creates a VPC with 2 subnets (1 public and 1 private) and an EC2 instance in the public subnet'

Parameters:
  VpcCIDR:
    Description: 'CIDR block for the VPC'
    Type: 'String'
    Default: '10.0.0.0/16'
  
  PublicSubnetCIDR:
    Description: 'CIDR block for the public subnet'
    Type: 'String'
    Default: '10.0.1.0/24'

  PrivateSubnetCIDR:
    Description: 'CIDR block for the private subnet'
    Type: 'String'
    Default: '10.0.2.0/24'

Resources:
  MyVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: !Ref 'VpcCIDR'
      EnableDnsSupport: true
      EnableDnsHostnames: true

  PublicSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref 'MyVPC'
      CidrBlock: !Ref 'PublicSubnetCIDR'
  
  PrivateSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref 'MyVPC'
      CidrBlock: !Ref 'PrivateSubnetCIDR'

  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'

  AttachGateway:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref 'MyVPC'
      InternetGatewayId: !Ref 'InternetGateway'

  PublicRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref 'MyVPC'

  PublicRoute:
    Type: 'AWS::EC2::Route'
    DependsOn: 'AttachGateway'
    Properties:
      RouteTableId: !Ref 'PublicRouteTable'
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId: !Ref 'InternetGateway'

  PublicSubnetRouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref 'PublicSubnet'
      RouteTableId: !Ref 'PublicRouteTable'

  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: 't2.micro'
      ImageId: 'ami-0c55b159cbfafe1f0'
      SubnetId: !Ref 'PublicSubnet'
      KeyName: 'your-key-name'
      SecurityGroups:
        - !Ref 'EC2SecurityGroup'

  EC2SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Enable SSH access'
      SecurityGroupIngress:
        - IpProtocol: 'tcp'
          FromPort: '22'
          ToPort: '22'
          CidrIp: '0.0.0.0/0'

Outputs:
  VPCId:
    Description: 'VPC Id'
    Value: !Ref 'MyVPC'
  
  PublicSubnetId:
    Description: 'Public Subnet Id'
    Value: !Ref 'PublicSubnet'
  
  PrivateSubnetId:
    Description: 'Private Subnet Id'
    Value: !Ref 'PrivateSubnet'
  
  PublicRouteTableId:
    Description: 'Public Route Table Id'
    Value: !Ref 'PublicRouteTable'
  
  EC2InstancePublicIp:
    Description: 'Public IP address of the EC2 instance'
    Value: !GetAtt EC2Instance.PublicIp
