---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: three-tier
spec:
  template:
    metadata:
      labels:
        app: three-tier
    spec:
      containers:
        - name: backend-server
          image: mehulbisen/mehul-repo:backendf
          ports:
            - containerPort: 8080
  replicas: 3
  selector:
    matchLabels:
      app: three-tier
  strategy: 
    type: RollingUpdate

...

---
apiVersion: v1
kind: Service
metadata: 
  name: my-service
  labels:
    app: three-tier
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: three-tier

...



