FROM centos:7
RUN install java-11-openjdk -y
ADD https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.87/bin/apache-tomcat-9.0.87.tar.gz ./
RUN tar -xzf apache-tomcat-9.0.87.tar.gz /opt/
ADD https://s3-us-west-2.amazonaws.com/studentapi-cit/student.war /opt/apache-tomcat-9.0.87/webapps/
ADD https://s3-us-west-2.amazonaws.com/studentapi-cit/mysql-connector.jar /opt/apache-tomcat-9.0.87/lib
COPY context.xml /opt/apache-tomcat-9.0.87/conf/
EXPOSE 8080
CMD ["./opt/apache-tomcat-9.0.87/bin/catalina.sh", "start"]