---
apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: my-deployment
  labels:
    app: my-app
    env: dev

spec:
  template:
    metadata:
      labels:
        app: my-app
        env: dev
  spec: 
    container: 
      - name: demo-container
        image: httpd
        ports:
          - containerPort: 80
  replicas: 4
  selector:
    matchLabels:
      app: my-app
  strategy:
    type: RollingUpdate
...

---
apiVersion: v1 
kind: Service 
metadata: 
  name: my-svc
  labels:
    app: my-app
    env: dev
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: my-app

...