---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: demo-deployment
  labels:
    app: demo-app
spec:
  template:
    metadata: 
      labels:
        app: demo-app
    spec:
      containers:
        - name: backend-server
          image: nginx
          ports:
            - containerPort: 80
  replicas: 3
  selector:
    matchLabels: 
      app: demo-app
  strategy: 
    type: RollingUpdate
...

---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
  labels:
    app: demo-app
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: demo-app
...


  

