---
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: salo-dep
  labels:
    salo: dep 
spec: 
  replicas: 3 
  selector:
    matchLabels:
      salo: dep 
  template: 
    metadata: 
      labels: 
        salo: dep 
    spec: 
      containers: 
        - name: salo-pod
          image: httpd 
          ports: 
            - containerPort: 80
... 
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: salo-svc 
  labels: 
    salo: dep 
spec: 
  ports:
    - port: 80 
      targetPort: 80
      protocol: TCP 
  type: NodePort 
  selector:
    salo: dep 
...