FROM centos:7
RUN yum install java-11-openjdk -y
ADD https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.87/bin/apache-tomcat-9.0.87.tar.gz ./
RUN tar -xzf apache-tomcat-9.0.87.tar.gz -C /opt/
ADD https://s3-us-west-2.amazonaws.com/studentapi-cit/student.war /opt/apache-tomcat-9.0.87/webapps/
ADD https://s3-us-west-2.amazonaws.com/studentapi-cit/mysql-connector.jar /opt/apache-tomcat-9.0.87/lib/mysql-connector.jar
COPY context.xml /opt/apache-tomcat-9.0.87/conf/   
EXPOSE 8080
WORKDIR /opt/apache-tomcat-9.0.87/bin/
CMD ["./catalina.sh", "run"]



